### ISSUE TITLE
Feature: Leaderboard

### ISSUE THREAD

**Issue by Milo-Johnson** [ENG1-Group-2/ENG1-ASSESSMENT-TWO#33]
Complete leaderboard implementation. Most methods required exist, and the data can be saved to the settings.txt file, method calls just need to be added and display text added.

**Comment by mistryvivek** [comment]
Just a suggestion but if we keep a high score for each game mode with each timer and have a json file (see my ticket on the points)
![image](https://user-images.githubusercontent.com/85026959/230972743-14c299bb-2f5a-46bf-a942-0d83c3daf682.png)
To find ur mode, you just have 2 nodes, then powerups and number (the latter two should be variables in scenerio game master). If it doesn't exist, create it. If it does, compare to existing and replace where required. Also would make the game easier to test.
