### ISSUE TITLE
Tests: Chef initialisation problems with stacks

### ISSUE THREAD

**Issue by lchlan** [ENG1-Group-2/ENG1-ASSESSMENT-TWO#4]
can't create a new stack in one go, must create a blank and then push contents
should add exception tests
:)

**Comment by mistryvivek** [comment]
Just to extend on this, comparing stacks seems inefficient now, as we have been using multiple lines of code (while duplicating .add) to add to the test stack. Further research and a change needs to be made.

**Comment by mistryvivek** [comment]
Tests have been rewritten for a previous ticket for this
